#!/bin/sh
### BEGIN INIT INFO
# Provides:          metalplayer
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop metalplayer
### END INIT INFO
#/usr/sbin/update-rc.d metalplayer defaults
#/usr/sbin/update-rc.d -f metalplayer remove

PATH=/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin
 
. /lib/lsb/init-functions
 
do_start () {
    log_begin_msg "Starting MetalPlayer Server..."
        start-stop-daemon --start --oknodo --make-pidfile /var/run/metalplayer.pid --background --pidfile /var/run/metalplayer.pid --startas /usr/local/bin/metalplayer
        log_end_msg $?
}
do_stop () {
    log_begin_msg "Stopping MetalPlayer Server..."
        start-stop-daemon --stop --oknodo --pidfile /var/run/metalplayer.pid
        rm -f /var/run/metalplayer.pid
        log_end_msg $?
}
 
case "$1" in
  start)
    do_start
    ;;
  restart|reload|force-reload)
        do_stop
        do_start
    ;;
  stop)
    do_stop
    ;;
  *)
    echo "Usage: $0 start|stop" >&2
    exit 3
    ;;
esac
